# Generated by Django 4.2.3 on 2023-07-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_licensing', '0002_remove_subscription_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='activation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
